###
GET http://localhost:8080/api/v1/boards
Accept: application/json

###
GET http://localhost:8080/api/v1/boards?limit=1
Accept: application/json

###
GET http://localhost:8080/api/v1/boards/1
Accept: application/json

###
POST http://localhost:8080/api/v1/boards
Accept: application/json
Content-Type: application/json

{
  "key": "test",
  "name": "테스트"
}

###
PUT http://localhost:8080/api/v1/boards/1
Accept: application/json
Content-Type: application/json

{
  "name": "테스트2"
}
