###
GET http://localhost:8080/api/v1/thread?board_id=1
Accept: application/json

###
GET http://localhost:8080/api/v1/thread?board_id=1&limit=3&offset=3
Accept: application/json

###
GET http://localhost:8080/api/v1/thread?id=1
Accept: application/json
Content-Type: application/json

###
POST http://localhost:8080/api/v1/thread
Accept: application/json
Content-Type: application/json

{
  "board_id": 1,
  "title": "test",
  "password": "test"
}

###
PUT http://localhost:8080/api/v1/thread/24?confirm=true
Accept: application/json

###
PUT http://localhost:8080/api/v1/threads/1
Accept: application/json
Content-Type: application/json

{
  "name": "테스트2"
}
